services:
  db:
    container_name: ${DATABASE_NAME}
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    container_name: ${DOCKER_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

volumes:
  pgdata:
